### ISSUE TITLE
Received invalid UserInfo request

### ISSUE THREAD

**Issue by alexanderfrei** [vaulttec/sonar-auth-oidc#61]
Hello,

I am using Sonarqube, 8.9.6.

OpenID connect with our company IdP is failing and I received warning:

Received invalid UserInfo request. Audience 'microsoft:identityserver:77badab9-ba8d-4528-a7fc-1d0feddcee0e' in the access token is not same as the identifier of the UserInfo relying party trust 'urn:microsoft:userinfo'.","error":"invalid_token"}

I think my IdP guy said to me, "userinfo endpoint" cannot be used anymore, instead they urge us to use claims to get user attributes.

Is this related to this issue that I am facing?

2022.01.26 10:42:03 WARN  web[AX6VwkYsi57i8C/ZAAAm][o.s.s.a.AuthenticationError] Fail to callback authentication with 'oidc'
java.lang.IllegalStateException: UserInfo request failed: {"error_description":"MSIS9921: Received invalid UserInfo request. Audience 'microsoft:identityserver:77badab9-ba8d-4528-a7fc-1d0feddcee0e' in the access token is not same as the identifier of the UserInfo relying party trust 'urn:microsoft:userinfo'.","error":"invalid_token"}
        at org.vaulttec.sonarqube.auth.oidc.OidcClient.getUserInfo(OidcClient.java:154)
        at org.vaulttec.sonarqube.auth.oidc.OidcIdentityProvider.callback(OidcIdentityProvider.java:89)
        at org.sonar.server.authentication.OAuth2CallbackFilter.handleOAuth2Provider(OAuth2CallbackFilter.java:92)
        at org.sonar.server.authentication.OAuth2CallbackFilter.handleProvider(OAuth2CallbackFilter.java:75)
        at org.sonar.server.authentication.OAuth2CallbackFilter.doFilter(OAuth2CallbackFilter.java:68)
        at org.sonar.server.platform.web.MasterServletFilter$GodFilterChain.doFilter(MasterServletFilter.java:139)
        at org.sonar.server.authentication.DefaultAdminCredentialsVerifierFilter.doFilter(DefaultAdminCredentialsVerifierFilter.java:89)
        at org.sonar.server.platform.web.MasterServletFilter$GodFilterChain.doFilter(MasterServletFilter.java:139)
        at org.sonar.server.plugins.PluginsRiskConsentFilter.doFilter(PluginsRiskConsentFilter.java:77)
        at org.sonar.server.platform.web.MasterServletFilter$GodFilterChain.doFilter(MasterServletFilter.java:139)
        at org.sonar.server.platform.web.MasterServletFilter.doFilter(MasterServletFilter.java:108)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:194)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:167)
        at org.sonar.server.platform.web.UserSessionFilter.doFilter(UserSessionFilter.java:81)
        at org.sonar.server.platform.web.UserSessionFilter.doFilter(UserSessionFilter.java:68)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:194)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:167)
        at org.sonar.server.platform.web.CacheControlFilter.doFilter(CacheControlFilter.java:76)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:194)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:167)
        at org.sonar.server.platform.web.SecurityServletFilter.doHttpFilter(SecurityServletFilter.java:76)
        at org.sonar.server.platform.web.SecurityServletFilter.doFilter(SecurityServletFilter.java:48)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:194)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:167)
        at org.sonar.server.platform.web.RedirectFilter.doFilter(RedirectFilter.java:58)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:194)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:167)
        at org.sonar.server.platform.web.RequestIdFilter.doFilter(RequestIdFilter.java:66)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:194)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:167)
        at org.sonar.server.platform.web.RootFilter.doFilter(RootFilter.java:62)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:194)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:167)
        at org.apache.catalina

**Comment by tjuerge** [comment]
It seems that the ID token (for the requested [scopes `openid profile email`](https://auth0.com/docs/get-started/apis/scopes/openid-connect-scopes)) returned by your ADFS does not contain the [standard claims](https://openid.net/specs/openid-connect-core-1_0.html#StandardClaims) `name` and `preferred_username` (and `groups` if 'Synchronize Groups' is enabled). But these claims are needed by this plugin to access or create a SQ user. Therefore the plugin tries to retrieve these missing claims from the ADFS userinfo endpoint instead. But your ADFS behaves strange with the `aud` parameter of the bearer access token and the relying party identifiers configured in ADFS (as described [here](https://github.com/IdentityServer/IdentityServer4/issues/812)).

In both cases it's an issue with the configuration of your ADFS and can only be fixed by your ADFS admin.

**Comment by tjuerge** [comment]
It seems that in v2.0 of [Microsoft identity platform ID tokens](https://docs.microsoft.com/en-us/azure/active-directory/develop/id-tokens) both claims are available by default.

**Comment by sebgamby** [comment]
Hello,

Thank you for this question. Based on the analysis provided by @tjuerge I have been able to get OIDC working for Sonarqube with ADFS as Identity Provider. If it helps, please find below the Powershell script used for (re-)creating the the application group in ADFS. Please note:
- A custom rule is required for the claim 'preferred_name' (no option in the default LDAP rule)
- The scope 'allatclaims' must be selected in the ADFS settings, not necessary for the Sonarqube settings
- If you want to synchronize groups, each potential user must be member of at least two groups. Otherwise, ADFS provides a string for the 'group' claim in the access token instead of the expected JSON array

`$appGroupName= "sonarqube_uat"
$appGroupId="03764FB0-95CB-45FA-861A-03B25D203D40"
$clientId="C9FCA520-A344-4F21-97C9-2AC0AC86FB9D"
$redirectUri="https://sonar.contoso.com/oauth2/callback/oidc"

# each "rule block" must be followed by an empty line, including the last one
$rules = @"
@RuleTemplate = "LdapClaims"
@RuleName = "Basic LDAP claims"
c:[Type == "http://schemas.microsoft.com/ws/2008/06/identity/claims/windowsaccountname", Issuer == "AD AUTHORITY"]
 => issue(store = "Active Directory", types = ("http://schemas.xmlsoap.org/ws/2005/05/identity/claims/upn", "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/givenname", "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/surname", "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress"), query = ";sAMAccountName,givenName,sn,mail;{0}", param = c.Value);

@RuleName = "Custom Rule - preferred_username"
c:[Type == "http://schemas.microsoft.com/ws/2008/06/identity/claims/windowsaccountname", Issuer == "AD AUTHORITY"]
 => issue(store = "Active Directory", types = ("preferred_username"), query = ";sAMAccountName;{0}", param = c.Value);

@RuleName = "Custom Rule - name"
c1:[type == "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/givenname" ]
&&  c2:[type == "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/surname"]
=> issue(type = "name", value = c1.value + "  " + c2.value);

@RuleTemplate = "EmitGroupClaims"
@RuleName = "Group claim - WORKER"
c:[Type == "http://schemas.microsoft.com/ws/2008/06/identity/claims/groupsid", Value == "S-1-5-21-4240864409-1924352195-1241020549-1109", Issuer == "AD AUTHORITY"]
 => issue(Type = "groups", Value = "WORKER", Issuer = c.Issuer, OriginalIssuer = c.OriginalIssuer, ValueType = c.ValueType);

@RuleTemplate = "EmitGroupClaims"
@RuleName = "Group claim - ADMIN"
c:[Type == "http://schemas.microsoft.com/ws/2008/06/identity/claims/groupsid", Value == "S-1-5-21-4240864409-1924352195-1241020549-1124", Issuer == "AD AUTHORITY"]
 => issue(Type = "groups", Value = "ADMIN", Issuer = c.Issuer, OriginalIssuer = c.OriginalIssuer, ValueType = c.ValueType);

"@

Clear-Host

$group = Get-AdfsApplicationGroup -ApplicationGroupIdentifier $appGroupId

if ($null -ne $group)
{
    Remove-AdfsApplicationGroup -TargetApplicationGroupIdentifier $appGroupId 
}

new-adfsapplicationgroup -name $appGroupName -applicationgroupidentifier $appGroupId 
$server = add-adfsserverapplication -applicationgroupidentifier $appGroupId -identifier $clientId -name "$appGroupName - server application" -redirecturi $redirectUri -generateclientsecret
add-adfswebapiapplication -applicationgroupidentifier $appGroupId -identifier $clientId -name "$appGroupName - web api" -accesscontrolpolicyname "permit everyone for intranet access" -IssuanceTransformRules $rules
grant-adfsapplicationpermission -clientroleidentifier $clientId -serverroleidentifier $clientId -scopenames "openid", "email", "profile", "allatclaims"

$secret = $server.clientsecret
write-host "the client secret is $secret"`
